apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: systesting
spec:
  params:
    - name: run-id
      type: string
      default: systesting-demo
  workspaces:
    - name: manifest
  tasks:
    - name: env-prepare
      taskRef:
        name: systesting-prepare-env
      params:
        - name: run-id
          value: "$(params.run-id)"
      workspaces:
        - name: manifest
          workspace: manifest
    - name: workload-prepare
      taskRef:
        name: systesting-workload-prepare
      runAfter:
        - env-prepare
      params:
        - name: run-id
          value: "$(params.run-id)"
      workspaces:
        - name: manifest
          workspace: manifest
    - name: workload-run
      taskRef:
        name: systesting-workload-run
      runAfter:
        - workload-prepare
      params:
        - name: run-id
          value:
          value: "$(params.run-id)"
      workspaces:
        - name: manifest
          workspace: manifest
    - name: sleep-10m
      runAfter:
        - workload-prepare
      taskRef:
        name: systesting-sleep
      params:
        - name: duration
          value: "600"
    - name: scale-cluster
      taskRef:
        name: systesting-ops-resource
      runAfter:
        - sleep-10m
      params:
        - name: run-id
          value: "$(params.run-id)"
      workspaces:
        - name: manifest
          workspace: manifest
    - name: teardown
      taskRef:
        name: systesting-teardown
      runAfter:
        - workload-run
      params:
        - name: run-id
          value: "$(params.run-id)"
