apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: systesting-50
spec:
  serviceAccountName: system-testing
  pipelineRef:
    name: systesting
  workspaces:
    - name: manifest
      emptyDir: {}
  params:
    - name: run-id
      value: systesting-demo
