apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-workload-31
spec:
  serviceAccountName: system-testing
  taskRef:
    name: test-workload
  workspaces:
    - name: manifest
      emptyDir: {}
